### ISSUE TITLE
應用程式要怎麼放進去？

### ISSUE THREAD

**Issue by justgps** [kevingo/Go-Small-Docker-Image#9]
看不到你的main.go在那裡被處理？程式碼到後來變成 app！？可以解釋一下嗎？ Thanks.

**Comment by kevingo** [comment]
Hi @justgps 您可以參考 golang onbuild 的 [Dockerfile](https://github.com/docker-library/golang/blob/master/1.7/onbuild/Dockerfile)，裡面就可以看到為什麼會產生 app 的執行檔。main.go 就是在 onbuild 的時候被執行了

**Comment by kevingo** [comment]
@justgps 有解決您的疑問嗎？有任何問題歡迎討論。

**Comment by justgps** [comment]
@kevingo 感謝您，中間接上 golang onbuild 的Dockerfile後，整個程序就連貫起來，現下已經完全了解為何會有app檔的出現，感恩。

**Comment by kevingo** [comment]
@justgps 沒問題～那我關掉這個 issue 了，感謝交流
